[[redirects]]
from = "/arcane"
to = "/frames/arcane/arcane.html"
status = 200

[[redirects]]
from = "/BMW"
to = "/frames/golden/BMW.html"
status = 200

[[redirects]]
from = "/Bryant"
to = "/frames/white/Bryant.html"
status = 200

[[redirects]]
from = "/CR7"
to = "/frames/white/CR7.html"
status = 200

[[redirects]]
from = "/Galaxy"
to = "/frames/white/Galaxy.html"
status = 200

[[redirects]]
from = "/Ghost of Tsushima"
to = "/frames/white/Ghost of Tsushima.html"
status = 200
